/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ffmpeg-n3.3-and-ff3.3--ijk0.8.0--20170615--001-and-musicallyapp-20171016"
#endif /* AVUTIL_FFVERSION_H */
